name: core_x
description: Core-X Workshop mobile application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^8.0.1
  http: ^0.12.2
  flutter_svg: ^0.19.0
  carousel_slider: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/imgs/logo.png
    - assets/icons/cabinet.svg
    - assets/icons/cards.svg
    - assets/icons/fan.svg
    - assets/icons/graphic_card.svg
    - assets/icons/hdd.svg
    - assets/icons/motherboard.svg
    - assets/icons/others.svg
    - assets/icons/processor.svg
    - assets/icons/ram.svg
    - assets/icons/smps.svg
    - assets/icons/ssd.svg

  fonts:
    - family: GoogleSans
      fonts:
        - asset: assets/fonts/GoogleSansRegular.ttf

    - family: WorkSansSemiBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-SemiBold.ttf

    - family: WorkSansBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Bold.ttf

    - family: WorkSansMedium
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Medium.ttf